apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: wallet-engine

replicas:
  - name: wallet-engine
    count: 2

images:
  - name: harbor.157.180.105.202.nip.io/osonx/wallet-engine
    newTag: sha-84484774
