apiVersion: kustomize.dev/v1beta1
kind: Kustomization

namespace: wallet-engine

resources:
  - deployment.yaml

images:
  - name: harbor.157.180.105.202.nip.io/osonx/wallet-engine
    newTag: latest
